# Generated by Django 5.1.2 on 2024-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransferModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(max_length=50)),
                ("from_address", models.CharField(max_length=50)),
                ("to_address", models.CharField(max_length=50)),
                ("transaction_hash", models.TextField()),
                ("block_number", models.IntegerField()),
            ],
        ),
    ]
